# app/helpers/kt/components/datepicker_component.rb
module KT::Components::DatepickerComponent
  include KT::UI::Base::BaseUIHelper

  # ✅ SRP: Date picker input component
  def ui_datepicker(name:, value: nil, placeholder: "Select date", format: "Y-m-d", **options)
    input_id = options[:id] || "datepicker-#{SecureRandom.hex(4)}"
    classes = build_datepicker_class(options.delete(:class))

    content_tag(:div, class: "kt-datepicker-wrapper") do
      concat text_field_tag(name, value, class: classes, placeholder: placeholder,
                           data: { "kt-datepicker": true, "kt-datepicker-format": format }, **options)
      concat datepicker_trigger(input_id)
      concat datepicker_calendar(input_id)
    end
  end

  # ✅ SRP: Date range picker
  def ui_datepicker_range(start_name:, end_name:, start_value: nil, end_value: nil, **options)
    wrapper_id = "daterange-#{SecureRandom.hex(4)}"
    classes = build_datepicker_class(options.delete(:class))

    content_tag(:div, class: "kt-datepicker-range-wrapper", id: wrapper_id) do
      content_tag(:div, class: "flex gap-2") do
        concat text_field_tag(start_name, start_value, class: classes, placeholder: "Start date",
                             data: { "kt-datepicker-range": true, "kt-datepicker-range-type": "start" })
        concat content_tag(:span, "to", class: "self-center text-muted-foreground")
        concat text_field_tag(end_name, end_value, class: classes, placeholder: "End date",
                             data: { "kt-datepicker-range": true, "kt-datepicker-range-type": "end" })
      end
      concat datepicker_calendar(wrapper_id, range: true)
    end
  end

  # ✅ SRP: Time picker input
  def ui_timepicker(name:, value: nil, placeholder: "Select time", format: "H:i", **options)
    input_id = options[:id] || "timepicker-#{SecureRandom.hex(4)}"
    classes = build_timepicker_class(options.delete(:class))

    content_tag(:div, class: "kt-timepicker-wrapper") do
      concat text_field_tag(name, value, class: classes, placeholder: placeholder,
                           data: { "kt-timepicker": true, "kt-timepicker-format": format }, **options)
      concat timepicker_trigger(input_id)
      concat timepicker_dropdown(input_id)
    end
  end

  # ✅ SRP: DateTime picker (combined)
  def ui_datetimepicker(name:, value: nil, placeholder: "Select date & time", **options)
    input_id = options[:id] || "datetimepicker-#{SecureRandom.hex(4)}"
    classes = build_datetimepicker_class(options.delete(:class))

    content_tag(:div, class: "kt-datetimepicker-wrapper") do
      concat text_field_tag(name, value, class: classes, placeholder: placeholder,
                           data: { "kt-datetimepicker": true }, **options)
      concat datetimepicker_trigger(input_id)
      concat datetimepicker_container(input_id)
    end
  end

  private

  def datepicker_trigger(input_id)
    content_tag(:button, class: "kt-datepicker-trigger", type: "button",
                       data: { "kt-datepicker-toggle": input_id }) do
      ui_icon(name: "calendar", size: :sm)
    end
  end

  def datepicker_calendar(input_id, range: false)
    calendar_class = range ? "kt-datepicker-calendar-range" : "kt-datepicker-calendar"
    content_tag(:div, class: "#{calendar_class} hidden", id: "#{input_id}-calendar",
                       data: { "kt-datepicker-calendar": true, "kt-datepicker-target": input_id }) do
      # Calendar content would be generated by JavaScript
      content_tag(:div, "Calendar placeholder", class: "p-4 text-center text-muted-foreground")
    end
  end

  def timepicker_trigger(input_id)
    content_tag(:button, class: "kt-timepicker-trigger", type: "button",
                       data: { "kt-timepicker-toggle": input_id }) do
      ui_icon(name: "clock", size: :sm)
    end
  end

  def timepicker_dropdown(input_id)
    content_tag(:div, class: "kt-timepicker-dropdown hidden", id: "#{input_id}-dropdown",
                       data: { "kt-timepicker-dropdown": true, "kt-timepicker-target": input_id }) do
      # Time picker content would be generated by JavaScript
      content_tag(:div, "Time picker placeholder", class: "p-4 text-center text-muted-foreground")
    end
  end

  def datetimepicker_trigger(input_id)
    content_tag(:button, class: "kt-datetimepicker-trigger", type: "button",
                       data: { "kt-datetimepicker-toggle": input_id }) do
      ui_icon(name: "calendar-clock", size: :sm)
    end
  end

  def datetimepicker_container(input_id)
    content_tag(:div, class: "kt-datetimepicker-container hidden", id: "#{input_id}-container",
                       data: { "kt-datetimepicker-container": true, "kt-datetimepicker-target": input_id }) do
      # DateTime picker content would be generated by JavaScript
      content_tag(:div, "DateTime picker placeholder", class: "p-4 text-center text-muted-foreground")
    end
  end

  def build_datepicker_class(additional_class)
    classes = [ "kt-datepicker-input", "kt-input" ]
    classes << additional_class if additional_class
    classes.join(" ")
  end

  def build_timepicker_class(additional_class)
    classes = [ "kt-timepicker-input", "kt-input" ]
    classes << additional_class if additional_class
    classes.join(" ")
  end

  def build_datetimepicker_class(additional_class)
    classes = [ "kt-datetimepicker-input", "kt-input" ]
    classes << additional_class if additional_class
    classes.join(" ")
  end
end
