# app/helpers/kt/components/calendar_component.rb
module KT::Components::CalendarComponent
  include KT::BaseUiHelper

  # ✅ SRP: Basic calendar component
  def ui_calendar(events: [], view: :month, **options)
    calendar_id = options[:id] || "calendar-#{SecureRandom.hex(4)}"
    classes = build_calendar_class(options.delete(:class))

    content_tag(:div, class: classes, **options) do
      concat calendar_header(calendar_id, view)
      concat calendar_view(view, events, calendar_id)
    end
  end

  # ✅ SRP: Calendar with event creation
  def ui_calendar_with_events(events: [], allow_create: true, **options)
    calendar_id = options[:id] || "calendar-events-#{SecureRandom.hex(4)}"

    content_tag(:div, class: "kt-calendar-with-events") do
      concat calendar_toolbar(calendar_id, allow_create)
      concat ui_calendar(events: events, **options.merge(id: calendar_id))
    end
  end

  # ✅ SRP: Scheduler component
  def ui_scheduler(resources: [], events: [], time_slots: [], **options)
    scheduler_id = options[:id] || "scheduler-#{SecureRandom.hex(4)}"
    classes = build_scheduler_class(options.delete(:class))

    content_tag(:div, class: classes, **options) do
      concat scheduler_header(resources, scheduler_id)
      concat scheduler_grid(resources, events, time_slots, scheduler_id)
    end
  end

  private

  def calendar_header(calendar_id, view)
    content_tag(:div, class: "kt-calendar-header flex items-center justify-between p-4 border-b border-border") do
      concat calendar_navigation(calendar_id)
      concat calendar_view_selector(calendar_id, view)
    end
  end

  def calendar_navigation(calendar_id)
    content_tag(:div, class: "kt-calendar-nav flex items-center gap-2") do
      concat ui_button(icon: "chevron-left", variant: :ghost, size: :sm, data: { "kt-calendar-prev": calendar_id })
      concat content_tag(:h2, "December 2024", class: "kt-calendar-title text-lg font-semibold", data: { "kt-calendar-title": calendar_id })
      concat ui_button(icon: "chevron-right", variant: :ghost, size: :sm, data: { "kt-calendar-next": calendar_id })
    end
  end

  def calendar_view_selector(calendar_id, current_view)
    content_tag(:div, class: "kt-calendar-views flex border border-border rounded") do
      concat ui_button(text: "Month", variant: current_view == :month ? :default : :ghost, size: :sm, class: "rounded-r-none", data: { "kt-calendar-view": "month" })
      concat ui_button(text: "Week", variant: current_view == :week ? :default : :ghost, size: :sm, class: "rounded-none", data: { "kt-calendar-view": "week" })
      concat ui_button(text: "Day", variant: current_view == :day ? :default : :ghost, size: :sm, class: "rounded-l-none", data: { "kt-calendar-view": "day" })
    end
  end

  def calendar_view(view, events, calendar_id)
    case view
    when :month
      calendar_month_view(events, calendar_id)
    when :week
      calendar_week_view(events, calendar_id)
    when :day
      calendar_day_view(events, calendar_id)
    end
  end

  def calendar_month_view(events, calendar_id)
    content_tag(:div, class: "kt-calendar-month", data: { "kt-calendar-month": calendar_id }) do
      concat calendar_weekdays_header
      concat calendar_month_grid(events, calendar_id)
    end
  end

  def calendar_weekdays_header
    weekdays = %w[Sun Mon Tue Wed Thu Fri Sat]
    content_tag(:div, class: "kt-calendar-weekdays grid grid-cols-7 border-b border-border") do
      safe_join(weekdays.map { |day| content_tag(:div, day, class: "kt-calendar-weekday p-2 text-center text-sm font-medium text-muted-foreground") })
    end
  end

  def calendar_month_grid(events, calendar_id)
    content_tag(:div, class: "kt-calendar-grid grid grid-cols-7", data: { "kt-calendar-grid": calendar_id }) do
      # Calendar days would be generated by JavaScript
      35.times do |i|
        concat calendar_day_cell(i + 1, events.select { |e| e[:date] == i + 1 }, calendar_id)
      end
    end
  end

  def calendar_day_cell(day, day_events, calendar_id)
    content_tag(:div, class: "kt-calendar-day min-h-[120px] p-2 border-r border-b border-border", data: { "kt-calendar-day": day }) do
      concat content_tag(:div, day, class: "kt-calendar-day-number text-sm font-medium mb-1")
      concat calendar_day_events(day_events, calendar_id)
    end
  end

  def calendar_day_events(events, calendar_id)
    content_tag(:div, class: "kt-calendar-events space-y-1") do
      safe_join(events.first(3).map { |event| calendar_event_badge(event, calendar_id) })
      concat calendar_more_events(events.size - 3) if events.size > 3
    end
  end

  def calendar_event_badge(event, calendar_id)
    content_tag(:div, event[:title], class: "kt-calendar-event text-xs p-1 rounded truncate #{event[:color] || 'bg-primary text-primary-foreground'}",
                data: { "kt-calendar-event": event[:id] })
  end

  def calendar_more_events(count)
    content_tag(:div, "+#{count} more", class: "kt-calendar-more text-xs text-muted-foreground p-1")
  end

  def calendar_week_view(events, calendar_id)
    content_tag(:div, class: "kt-calendar-week", data: { "kt-calendar-week": calendar_id }) do
      # Week view implementation
      content_tag(:div, "Week view placeholder", class: "p-8 text-center text-muted-foreground")
    end
  end

  def calendar_day_view(events, calendar_id)
    content_tag(:div, class: "kt-calendar-day", data: { "kt-calendar-day": calendar_id }) do
      # Day view implementation
      content_tag(:div, "Day view placeholder", class: "p-8 text-center text-muted-foreground")
    end
  end

  def calendar_toolbar(calendar_id, allow_create)
    content_tag(:div, class: "kt-calendar-toolbar flex items-center justify-between p-4 border-b border-border") do
      concat calendar_filters(calendar_id)
      if allow_create
        concat ui_button(text: "New Event", icon: "plus", data: { "kt-calendar-create": calendar_id })
      end
    end
  end

  def calendar_filters(calendar_id)
    content_tag(:div, class: "kt-calendar-filters flex gap-2") do
      concat select_tag("calendar_filter", options_for_select(["All Events", "My Events", "Team Events"]), class: "kt-input", data: { "kt-calendar-filter": calendar_id })
    end
  end

  def scheduler_header(resources, scheduler_id)
    content_tag(:div, class: "kt-scheduler-header flex border-b border-border") do
      concat content_tag(:div, "", class: "kt-scheduler-time-column w-20 border-r border-border") # Time column header
      safe_join(resources.map { |resource| content_tag(:div, resource[:name], class: "kt-scheduler-resource flex-1 p-2 text-center font-medium border-r border-border") })
    end
  end

  def scheduler_grid(resources, events, time_slots, scheduler_id)
    content_tag(:div, class: "kt-scheduler-grid flex overflow-auto", data: { "kt-scheduler": scheduler_id }) do
      concat scheduler_time_column(time_slots)
      safe_join(resources.map { |resource| scheduler_resource_column(resource, events.select { |e| e[:resource_id] == resource[:id] }, time_slots) })
    end
  end

  def scheduler_time_column(time_slots)
    content_tag(:div, class: "kt-scheduler-time-column w-20 border-r border-border") do
      safe_join(time_slots.map { |slot| content_tag(:div, slot, class: "kt-scheduler-time-slot h-12 p-2 text-xs text-muted-foreground border-b border-border") })
    end
  end

  def scheduler_resource_column(resource, resource_events, time_slots)
    content_tag(:div, class: "kt-scheduler-resource-column flex-1 border-r border-border relative") do
      # Time slots background
      safe_join(time_slots.map { |slot| content_tag(:div, "", class: "kt-scheduler-slot h-12 border-b border-border") })

      # Events
      safe_join(resource_events.map { |event| scheduler_event(event) })
    end
  end

  def scheduler_event(event)
    style = "top: #{calculate_event_top(event)}px; height: #{calculate_event_height(event)}px;"
    content_tag(:div, event[:title], class: "kt-scheduler-event absolute left-0 right-0 p-1 text-xs rounded #{event[:color] || 'bg-primary text-primary-foreground'}",
                style: style, data: { "kt-scheduler-event": event[:id] })
  end

  def calculate_event_top(event)
    # Calculate top position based on event start time
    0 # Placeholder
  end

  def calculate_event_height(event)
    # Calculate height based on event duration
    48 # Placeholder
  end

  def build_calendar_class(additional_class)
    classes = ["kt-calendar", "border border-border rounded-lg bg-background"]
    classes << additional_class if additional_class
    classes.join(" ")
  end

  def build_scheduler_class(additional_class)
    classes = ["kt-scheduler", "border border-border rounded-lg bg-background"]
    classes << additional_class if additional_class
    classes.join(" ")
  end
end